"""Phase 3 – Interactive planning + Copilot instructions generation."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from koteguard.models import PlanModel, ProjectInfo, WorkspaceModel


# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------


def _h2(title: str, items: list[str]) -> str:
    lines = [f"## {title}", ""]
    for item in items:
        lines.append(f"- {item}")
    lines.append("")
    return "\n".join(lines)


def _h2_text(title: str, body: str) -> str:
    return f"## {title}\n\n{body}\n\n"


# ---------------------------------------------------------------------------
# PLAN.md
# ---------------------------------------------------------------------------


def render_plan(plan: PlanModel) -> str:
    """Render a PlanModel to a PLAN.md string."""
    lines: list[str] = [
        f"# {plan.title}",
        "",
        f"> Generated by KoteGuard on {datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
    ]

    lines.append(_h2("Objectives", plan.objectives))
    lines.append("## Tasks\n")
    for i, task in enumerate(plan.tasks, 1):
        lines.append(f"{i}. {task}")
    lines.append("")
    lines.append(_h2("Definition of Done", plan.definition_of_done))
    lines.append(f"## Estimated Time\n\n{plan.estimated_time}\n")
    if plan.risks:
        lines.append(_h2("Risks", plan.risks))

    return "\n".join(lines)


def parse_plan(markdown: str) -> PlanModel:
    """Parse a PLAN.md markdown string back into a PlanModel."""

    def _extract_h1(text: str) -> str:
        m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
        return m.group(1).strip() if m else "Untitled Plan"

    def _extract_section_list(text: str, section: str) -> list[str]:
        pattern = rf"##\s+{re.escape(section)}\s*\n(.*?)(?=^##|\Z)"
        m = re.search(pattern, text, re.MULTILINE | re.DOTALL)
        if not m:
            return []
        block = m.group(1)
        items: list[str] = []
        for line in block.splitlines():
            line = line.strip()
            # Bullet or numbered list
            m2 = re.match(r"^[-*•]\s+(.+)$", line)
            if m2:
                items.append(m2.group(1))
                continue
            m2 = re.match(r"^\d+\.\s+(.+)$", line)
            if m2:
                items.append(m2.group(1))
        return items

    def _extract_section_text(text: str, section: str) -> str:
        pattern = rf"##\s+{re.escape(section)}\s*\n(.*?)(?=^##|\Z)"
        m = re.search(pattern, text, re.MULTILINE | re.DOTALL)
        if not m:
            return ""
        return m.group(1).strip()

    return PlanModel(
        title=_extract_h1(markdown),
        objectives=_extract_section_list(markdown, "Objectives") or ["(none)"],
        tasks=_extract_section_list(markdown, "Tasks") or ["(none)"],
        definition_of_done=_extract_section_list(markdown, "Definition of Done")
        or ["(none)"],
        estimated_time=_extract_section_text(markdown, "Estimated Time") or "unknown",
        risks=_extract_section_list(markdown, "Risks"),
    )


# ---------------------------------------------------------------------------
# WORKSPACE.md
# ---------------------------------------------------------------------------


def render_workspace(ws: WorkspaceModel) -> str:
    """Render a WorkspaceModel to a WORKSPACE.md string."""
    lines: list[str] = [
        f"# WORKSPACE: {ws.project_name}",
        "",
        "> Auto-generated by KoteGuard Phase 0 analysis.",
        "",
    ]

    lines.append(_h2("Tech Stack", ws.tech_stack))

    if ws.architecture:
        lines.append(_h2_text("Architecture", ws.architecture))

    if ws.conventions:
        lines.append(_h2("Conventions", ws.conventions))

    if ws.structure:
        lines.append("## Project Structure\n")
        for path, description in ws.structure.items():
            lines.append(f"- `{path}` – {description}")
        lines.append("")

    if ws.gotchas:
        lines.append(_h2("Gotchas / Watch-outs", ws.gotchas))

    return "\n".join(lines)


def workspace_from_project_info(info: ProjectInfo) -> WorkspaceModel:
    """Build a WorkspaceModel from a ProjectInfo (Phase 0 output)."""
    tech_stack: list[str] = info.frameworks.copy()
    if info.languages:
        tech_stack.extend(info.languages)
    if not tech_stack:
        tech_stack = [info.project_type.value]

    architecture = ""
    gotchas: list[str] = []
    structure: dict[str, str] = {}
    conventions: list[str] = []

    pt = info.project_type.value
    if pt == "android":
        architecture = (
            "Android application using Gradle build system. "
            "Standard Android project structure with app module."
        )
        if info.android_package:
            structure["app/src/main/"] = (
                f"Main source code (package: {info.android_package})"
            )
        gotchas.append("Never commit keystore files or google-services.json")
        gotchas.append("local.properties contains machine-specific SDK paths")
        conventions = ["Follow Android Kotlin style guide", "Prefer coroutines for async"]
        if info.android_min_sdk:
            conventions.append(f"Min SDK: {info.android_min_sdk}")

    elif pt == "ios":
        architecture = (
            "iOS application. "
            "Standard Xcode project structure."
        )
        if info.ios_bundle_id:
            structure["*.xcodeproj"] = f"Xcode project (bundle: {info.ios_bundle_id})"
        gotchas.append("Never commit .p12 certificates or .mobileprovision files")
        gotchas.append("GoogleService-Info.plist contains sensitive Firebase config")
        conventions = ["Follow Swift API Design Guidelines", "Prefer async/await for concurrency"]

    elif pt == "flutter":
        architecture = "Flutter cross-platform application."
        structure["lib/"] = "Dart application code"
        structure["pubspec.yaml"] = "Dependencies and project metadata"
        if info.flutter_sdk:
            conventions.append(f"Flutter SDK: >={info.flutter_sdk}")
        gotchas.append("Run `flutter pub get` after changing pubspec.yaml")

    elif pt == "react_native":
        architecture = "React Native cross-platform application."
        structure["src/"] = "Application source code"
        gotchas.append("Never commit .env files with API keys")

    if info.has_ci:
        conventions.append("CI is configured – ensure tests pass before merging")

    return WorkspaceModel(
        project_name=info.project_name,
        tech_stack=tech_stack,
        architecture=architecture,
        conventions=conventions,
        structure=structure,
        gotchas=gotchas,
    )


# ---------------------------------------------------------------------------
# Copilot instructions generation
# ---------------------------------------------------------------------------


def render_copilot_instructions(
    plan: PlanModel,
    workspace: WorkspaceModel,
    session_id: str,
) -> str:
    """Generate .github/copilot-instructions.md content."""
    tasks_md = "\n".join(f"{i}. {t}" for i, t in enumerate(plan.tasks, 1))
    dod_md = "\n".join(f"- {d}" for d in plan.definition_of_done)
    return f"""\
# Copilot Agent Instructions (KoteGuard Session: {session_id})

> **This is an isolated git worktree. You are NOT in the primary repository.**
> Changes here are safe to experiment with.

## Project: {workspace.project_name}

**Tech Stack:** {', '.join(workspace.tech_stack)}

## Your Mission: {plan.title}

### Tasks

{tasks_md}

### Definition of Done

{dod_md}

## Constraints

- Only modify files relevant to the tasks above.
- Do NOT run `git push` or create pull requests without human review.
- Do NOT access the internet except to install declared dependencies.
- Keep commits small and well-described.

## Estimated Time

{plan.estimated_time}
"""


def render_security_instructions(project_type: str = "unknown") -> str:
    """Generate .github/instructions/security.instructions.md content."""
    android_section = ""
    ios_section = ""

    if project_type in ("android", "monorepo", "flutter", "react_native", "unknown"):
        android_section = """
### Android

- NEVER read, copy, or output contents of: `*.jks`, `*.keystore`, `google-services.json`
- `local.properties` must never be committed
- Do not add signing config with hardcoded passwords
"""

    if project_type in ("ios", "monorepo", "flutter", "react_native", "unknown"):
        ios_section = """
### iOS

- NEVER read, copy, or output contents of: `*.p12`, `*.mobileprovision`, `GoogleService-Info.plist`
- Do not hardcode API keys or bundle IDs in source files
"""

    return f"""\
---
applyTo: "**"
---

# Security Instructions (KoteGuard)

> These instructions apply to ALL files in this worktree.

## Deny-by-Default Rules

1. **No secrets in source code** – never hardcode API keys, tokens, passwords.
2. **No git push** – humans review all changes before they leave this worktree.
3. **No branch creation outside kote/** – stay on the assigned branch.
4. **No file exfiltration** – do not print or upload file contents to external services.
{android_section}{ios_section}
## Allowed Git Commands

- `git status`, `git diff`, `git log` – read-only inspection
- `git add`, `git commit` – staging and committing changes
- `git stash` – temporary stash

## Forbidden Git Commands

- `git push` – forbidden without human review
- `git remote add` – forbidden
- `git clone` – forbidden inside worktree
"""
