"""Phase 3 – Interactive planning + Copilot instructions generation."""

from __future__ import annotations

import re
from datetime import UTC, datetime
from typing import Any

import yaml

from koteguard.models import PlanModel, ProjectInfo, TaskModel, WorkspaceModel

# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------


def _h2(title: str, items: list[str]) -> str:
    lines = [f"## {title}", ""]
    for item in items:
        lines.append(f"- {item}")
    lines.append("")
    return "\n".join(lines)


def _h2_text(title: str, body: str) -> str:
    return f"## {title}\n\n{body}\n\n"


# ---------------------------------------------------------------------------
# PLAN.md – render & parse (YAML front-matter spec)
# ---------------------------------------------------------------------------


def render_plan(plan: PlanModel) -> str:
    """Render a PlanModel to a PLAN.md string with YAML front-matter spec block."""
    # Serialize model to plain dict for YAML (PlanTask objects become dicts)
    data = plan.model_dump(mode="json")
    front_matter = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)

    # Human-readable markdown body
    tasks_md_lines = [
        f"{i}. [{('x' if t.done else ' ')}] {t.description}" for i, t in enumerate(plan.tasks, 1)
    ]
    tasks_md = "\n".join(tasks_md_lines)

    body_lines: list[str] = [
        f"# {plan.title}",
        "",
        f"> Generated by KoteGuard on {datetime.now(tz=UTC).strftime('%Y-%m-%d %H:%M UTC')}",
        "> The YAML block above is the machine-readable spec — edit task `done` fields there.",
        "",
        _h2("Objectives", plan.objectives),
        "## Tasks\n",
        tasks_md,
        "",
        _h2("Definition of Done", plan.definition_of_done),
        f"## Estimated Time\n\n{plan.estimated_time}\n",
    ]
    if plan.risks:
        body_lines.append(_h2("Risks", plan.risks))
    if plan.android_skills:
        body_lines.append(_h2("Android Skills", plan.android_skills))

    body_lines.append(
        "## Token & Context Rules (enforced by KoteGuard)\n\n"
        "- Batch all subtasks into ONE TASK.md (do not send multiple messages)\n"
        "- Use EDIT on this PLAN.md instead of follow-up messages\n"
        "- Choose model explicitly: fast/haiku for drafts, sonnet/full for real work\n"
        "- Prefer short, focused sessions — Copilot CLI auto-compacts at ~80% context window\n"
        "- After session: summarize key decisions back to WORKSPACE.md via kote cleanup --compact\n"
    )

    body = "\n".join(body_lines)
    return f"---\n{front_matter}---\n\n{body}"


def parse_plan(markdown: str) -> PlanModel:
    """Parse a PLAN.md string back into a PlanModel.

    Strategy:
    1. If YAML front-matter present → yaml.safe_load → PlanModel.model_validate
    2. yaml.YAMLError or no front-matter → legacy regex fallback
    """
    # --- Layer 1: YAML front-matter ---
    if markdown.startswith("---"):
        try:
            parts = markdown.split("---", 2)
            if len(parts) >= 3:
                fm_str = parts[1]
                data = yaml.safe_load(fm_str)
                if isinstance(data, dict) and "title" in data:
                    return PlanModel.model_validate(data)
        except (yaml.YAMLError, Exception):
            pass  # fall through to regex

    # --- Layer 2: Legacy regex fallback ---
    return _parse_plan_regex(markdown)


def _parse_plan_regex(markdown: str) -> PlanModel:
    """Legacy regex-based PLAN.md parser for files without YAML front-matter."""

    def _extract_h1(text: str) -> str:
        m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
        return m.group(1).strip() if m else "Untitled Plan"

    def _extract_section_list(text: str, section: str) -> list[str]:
        pattern = rf"##\s+{re.escape(section)}\s*\n(.*?)(?=^##|\Z)"
        m = re.search(pattern, text, re.MULTILINE | re.DOTALL)
        if not m:
            return []
        block = m.group(1)
        items: list[str] = []
        for line in block.splitlines():
            line = line.strip()
            m2 = re.match(r"^[-*•]\s+(.+)$", line)
            if m2:
                items.append(m2.group(1))
                continue
            m2 = re.match(r"^\d+\.\s+\[.\]\s+(.+)$", line)  # checkbox format
            if m2:
                items.append(m2.group(1))
                continue
            m2 = re.match(r"^\d+\.\s+(.+)$", line)
            if m2:
                items.append(m2.group(1))
        return items

    def _extract_section_text(text: str, section: str) -> str:
        pattern = rf"##\s+{re.escape(section)}\s*\n(.*?)(?=^##|\Z)"
        m = re.search(pattern, text, re.MULTILINE | re.DOTALL)
        if not m:
            return ""
        return m.group(1).strip()

    raw_tasks = _extract_section_list(markdown, "Tasks") or ["(none)"]
    # raw_tasks are strings — PlanModel validator will coerce to PlanTask
    return PlanModel(
        title=_extract_h1(markdown),
        objectives=_extract_section_list(markdown, "Objectives") or ["(none)"],
        tasks=raw_tasks,
        definition_of_done=_extract_section_list(markdown, "Definition of Done") or ["(none)"],
        estimated_time=_extract_section_text(markdown, "Estimated Time") or "unknown",
        risks=_extract_section_list(markdown, "Risks"),
        android_skills=_extract_section_list(markdown, "Android Skills"),
    )


# ---------------------------------------------------------------------------
# TASK.md – render & parse (YAML front-matter)
# ---------------------------------------------------------------------------


def render_task(task: TaskModel) -> str:
    """Serialize a TaskModel to a TASK.md string with YAML front-matter."""
    data = task.model_dump(mode="json")
    front_matter = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)

    constraints_md = "\n".join(f"- {c}" for c in task.constraints) or "- (none)"

    body = f"""\
# Task: {task.description}

**Session:** `{task.session_id}`

## Context

{task.context or "(none)"}

## Constraints

{constraints_md}
"""
    return f"---\n{front_matter}---\n\n{body}"


def parse_task(markdown: str) -> TaskModel:
    """Parse a TASK.md string back into a TaskModel.

    Prefers YAML front-matter; falls back to regex on error.
    """
    if markdown.startswith("---"):
        try:
            parts = markdown.split("---", 2)
            if len(parts) >= 3:
                data = yaml.safe_load(parts[1])
                if isinstance(data, dict) and "session_id" in data:
                    return TaskModel.model_validate(data)
        except (yaml.YAMLError, Exception):
            pass

    # Minimal regex fallback
    session_m = re.search(r"`([a-z0-9][a-z0-9\-]{2,})`", markdown)
    session_id = session_m.group(1) if session_m else "unknown-session"
    desc_m = re.search(r"^#\s+Task:\s+(.+)$", markdown, re.MULTILINE)
    description = desc_m.group(1).strip() if desc_m else "Unnamed task"
    return TaskModel(session_id=session_id, description=description)


# ---------------------------------------------------------------------------
# WORKSPACE.md
# ---------------------------------------------------------------------------


def render_workspace(ws: WorkspaceModel) -> str:
    """Render a WorkspaceModel to a WORKSPACE.md string."""
    lines: list[str] = [
        f"# WORKSPACE: {ws.project_name}",
        "",
        "> Auto-generated by KoteGuard Phase 0 analysis.",
        "",
    ]

    lines.append(_h2("Tech Stack", ws.tech_stack))

    if ws.architecture:
        lines.append(_h2_text("Architecture", ws.architecture))

    if ws.conventions:
        lines.append(_h2("Conventions", ws.conventions))

    if ws.structure:
        lines.append("## Project Structure\n")
        for path, description in ws.structure.items():
            lines.append(f"- `{path}` – {description}")
        lines.append("")

    if ws.gotchas:
        lines.append(_h2("Gotchas / Watch-outs", ws.gotchas))

    # Android Agent Stack section (v1.1)
    if ws.android_agent_stack:
        stack = ws.android_agent_stack
        lines.append("## Android Agent Stack\n")
        if stack.get("cli_version"):
            lines.append(f"- **Android CLI version:** {stack['cli_version']}")
        if stack.get("kb_status"):
            lines.append(f"- **Knowledge Base:** {stack['kb_status']}")
        if stack.get("enabled_skills"):
            lines.append("- **Enabled Skills:**")
            for skill in stack["enabled_skills"]:
                lines.append(f"  - {skill}")
        lines.append("")

    return "\n".join(lines)


def workspace_from_project_info(info: ProjectInfo) -> WorkspaceModel:
    """Build a WorkspaceModel from a ProjectInfo (Phase 0 output)."""
    tech_stack: list[str] = info.frameworks.copy()
    if info.languages:
        tech_stack.extend(info.languages)
    if not tech_stack:
        tech_stack = [info.project_type.value]

    architecture = ""
    gotchas: list[str] = []
    structure: dict[str, str] = {}
    conventions: list[str] = []
    android_agent_stack: dict[str, Any] = {}

    pt = info.project_type.value
    if pt == "android":
        architecture = (
            "Android application using Gradle build system. "
            "Standard Android project structure with app module."
        )
        if info.android_package:
            structure["app/src/main/"] = f"Main source code (package: {info.android_package})"
        gotchas.append("Never commit keystore files or google-services.json")
        gotchas.append("local.properties contains machine-specific SDK paths")
        conventions = ["Follow Android Kotlin style guide", "Prefer coroutines for async"]
        if info.android_min_sdk:
            conventions.append(f"Min SDK: {info.android_min_sdk}")

        # Populate Android agent stack
        android_agent_stack = {
            "cli_version": "available" if info.android_cli_available else "not detected",
            "kb_status": info.knowledge_base_status,
            "enabled_skills": info.detected_skills,
        }

        # Add doc summary findings to architecture
        if info.doc_summary:
            arch_findings: list[str] = []
            for _doc, headers in info.doc_summary.items():
                kw_found = [
                    h.replace("[keyword:", "").rstrip("]")
                    for h in headers
                    if h.startswith("[keyword:")
                ]
                if kw_found:
                    arch_findings.extend(kw_found)
            if arch_findings:
                unique_kw = list(dict.fromkeys(arch_findings))
                architecture += f" Detected architecture patterns: {', '.join(unique_kw[:5])}."

    elif pt == "ios":
        architecture = "iOS application. Standard Xcode project structure."
        if info.ios_bundle_id:
            structure["*.xcodeproj"] = f"Xcode project (bundle: {info.ios_bundle_id})"
        gotchas.append("Never commit .p12 certificates or .mobileprovision files")
        gotchas.append("GoogleService-Info.plist contains sensitive Firebase config")
        conventions = ["Follow Swift API Design Guidelines", "Prefer async/await for concurrency"]

    if info.has_ci:
        conventions.append("CI is configured – ensure tests pass before merging")

    return WorkspaceModel(
        project_name=info.project_name,
        tech_stack=tech_stack,
        architecture=architecture,
        conventions=conventions,
        structure=structure,
        gotchas=gotchas,
        android_agent_stack=android_agent_stack,
    )


# ---------------------------------------------------------------------------
# Copilot instructions generation
# ---------------------------------------------------------------------------


def render_copilot_instructions(
    plan: PlanModel,
    workspace: WorkspaceModel,
    session_id: str,
    android_cli_enabled: bool = True,
) -> str:
    """Generate .github/copilot-instructions.md content."""
    # Build task list with IDs so agent knows which id to reference
    tasks_md_lines = [
        f"{i}. `{t.id}`: {t.description}{' ✓' if t.done else ''}"
        for i, t in enumerate(plan.tasks, 1)
    ]
    tasks_md = "\n".join(tasks_md_lines)
    dod_md = "\n".join(f"- {d}" for d in plan.definition_of_done)

    # Android section — only shown when CLI is enabled
    android_section = ""
    if workspace.android_agent_stack and android_cli_enabled:
        stack = workspace.android_agent_stack
        skills = stack.get("enabled_skills", [])
        android_section = f"""
## Android Agent Stack

- **CLI Available:** {stack.get("cli_version", "unknown")}
- **Knowledge Base:** {stack.get("kb_status", "unknown")}

### Best Practices

- Always use `android` CLI commands for emulator and device management within the worktree
- Reference enabled skills when implementing features: {", ".join(skills) if skills else "none detected"}
- Prefer Jetpack Compose patterns where applicable
- Use Android-specific coroutine dispatchers (Dispatchers.IO for I/O, Dispatchers.Main for UI)
"""

    return f"""\
# Copilot Agent Instructions (KoteGuard Session: {session_id})

> **This is an isolated git worktree. You are NOT in the primary repository.**
> Changes here are safe to experiment with.

## Project: {workspace.project_name}

**Tech Stack:** {", ".join(workspace.tech_stack)}

## Your Mission: {plan.title}

### Tasks

{tasks_md}

### Definition of Done

{dod_md}

## Spec Updates (IMPORTANT)

When you complete a task, open `PLAN.md` and find the task in the `---` YAML block at the top.
Set `done: true` for that task entry. **Do not reformat any other part of the YAML block.**
Example: find `- id: t1` and change `done: false` to `done: true`.

## Constraints

- Only modify files relevant to the tasks above.
- Do NOT run `git push` or create pull requests without human review.
- Do NOT access the internet except to install declared dependencies.
- Keep commits small and well-described.

## Token & Context Discipline

- Batch all sub-tasks into a single response where possible
- Use fast/haiku models for drafts, full models for real implementation
- Sessions auto-compact at ~80% context window
{android_section}
## Estimated Time

{plan.estimated_time}
"""


def render_security_instructions(
    project_type: str = "unknown",
    android_cli_enabled: bool = True,
) -> str:
    """Generate .github/instructions/security.instructions.md content."""
    android_section = ""
    ios_section = ""

    if project_type in ("android", "monorepo", "unknown"):
        android_base = """
### Android

- NEVER read, copy, or output contents of: `*.jks`, `*.keystore`, `google-services.json`
- `local.properties` must never be committed
- Do not add signing config with hardcoded passwords
"""
        android_cli_block = """
### Android CLI Commands

**Allowed:** `android list avd`, `android list targets`, `android list sdk`
**Forbidden (outside worktree):** `android run`, `android emulator` – only valid inside a kote worktree
"""
        android_section = android_base + (android_cli_block if android_cli_enabled else "")

    if project_type in ("ios", "monorepo", "unknown"):
        ios_section = """
### iOS

- NEVER read, copy, or output contents of: `*.p12`, `*.mobileprovision`, `GoogleService-Info.plist`
- Do not hardcode API keys or bundle IDs in source files
"""

    return f"""\
---
applyTo: "**/*"
---

# Security Instructions (KoteGuard)

> These instructions apply to ALL files in this worktree.

## Deny-by-Default Rules

1. **No secrets in source code** – never hardcode API keys, tokens, passwords.
2. **No git push** – humans review all changes before they leave this worktree.
3. **No branch creation outside kote/** – stay on the assigned branch.
4. **No file exfiltration** – do not print or upload file contents to external services.
{android_section}{ios_section}
## Allowed Git Commands

- `git status`, `git diff`, `git log` – read-only inspection
- `git add`, `git commit` – staging and committing changes
- `git stash` – temporary stash

## Forbidden Git Commands

- `git push` – forbidden without human review
- `git remote add` – forbidden
- `git remote set-url` – forbidden
- `git clone` – forbidden inside worktree
"""
