"""Phase 3 – Interactive planning + Copilot instructions generation."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from koteguard.models import PlanModel, ProjectInfo, WorkspaceModel


# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------


def _h2(title: str, items: list[str]) -> str:
    lines = [f"## {title}", ""]
    for item in items:
        lines.append(f"- {item}")
    lines.append("")
    return "\n".join(lines)


def _h2_text(title: str, body: str) -> str:
    return f"## {title}\n\n{body}\n\n"


# ---------------------------------------------------------------------------
# PLAN.md
# ---------------------------------------------------------------------------


def render_plan(plan: PlanModel) -> str:
    """Render a PlanModel to a PLAN.md string."""
    lines: list[str] = [
        f"# {plan.title}",
        "",
        f"> Generated by KoteGuard on {datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
    ]

    lines.append(_h2("Objectives", plan.objectives))
    lines.append("## Tasks\n")
    for i, task in enumerate(plan.tasks, 1):
        lines.append(f"{i}. {task}")
    lines.append("")
    lines.append(_h2("Definition of Done", plan.definition_of_done))
    lines.append(f"## Estimated Time\n\n{plan.estimated_time}\n")
    if plan.risks:
        lines.append(_h2("Risks", plan.risks))
    if plan.android_skills:
        lines.append(_h2("Android Skills", plan.android_skills))

    # Token & Context Rules section
    lines.append(
        "## Token & Context Rules (enforced by KoteGuard)\n\n"
        "- Batch all subtasks into ONE TASK.md (do not send multiple messages)\n"
        "- Use EDIT on this PLAN.md instead of follow-up messages\n"
        "- Choose model explicitly: fast/haiku for drafts, sonnet/full for real work\n"
        "- Prefer short, focused sessions — Copilot CLI auto-compacts at ~80% context window\n"
        "- After session: summarize key decisions back to WORKSPACE.md via kote cleanup --compact\n"
    )

    return "\n".join(lines)


def parse_plan(markdown: str) -> PlanModel:
    """Parse a PLAN.md markdown string back into a PlanModel."""

    def _extract_h1(text: str) -> str:
        m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
        return m.group(1).strip() if m else "Untitled Plan"

    def _extract_section_list(text: str, section: str) -> list[str]:
        pattern = rf"##\s+{re.escape(section)}\s*\n(.*?)(?=^##|\Z)"
        m = re.search(pattern, text, re.MULTILINE | re.DOTALL)
        if not m:
            return []
        block = m.group(1)
        items: list[str] = []
        for line in block.splitlines():
            line = line.strip()
            m2 = re.match(r"^[-*•]\s+(.+)$", line)
            if m2:
                items.append(m2.group(1))
                continue
            m2 = re.match(r"^\d+\.\s+(.+)$", line)
            if m2:
                items.append(m2.group(1))
        return items

    def _extract_section_text(text: str, section: str) -> str:
        pattern = rf"##\s+{re.escape(section)}\s*\n(.*?)(?=^##|\Z)"
        m = re.search(pattern, text, re.MULTILINE | re.DOTALL)
        if not m:
            return ""
        return m.group(1).strip()

    return PlanModel(
        title=_extract_h1(markdown),
        objectives=_extract_section_list(markdown, "Objectives") or ["(none)"],
        tasks=_extract_section_list(markdown, "Tasks") or ["(none)"],
        definition_of_done=_extract_section_list(markdown, "Definition of Done")
        or ["(none)"],
        estimated_time=_extract_section_text(markdown, "Estimated Time") or "unknown",
        risks=_extract_section_list(markdown, "Risks"),
        android_skills=_extract_section_list(markdown, "Android Skills"),
    )


# ---------------------------------------------------------------------------
# WORKSPACE.md
# ---------------------------------------------------------------------------


def render_workspace(ws: WorkspaceModel) -> str:
    """Render a WorkspaceModel to a WORKSPACE.md string."""
    lines: list[str] = [
        f"# WORKSPACE: {ws.project_name}",
        "",
        "> Auto-generated by KoteGuard Phase 0 analysis.",
        "",
    ]

    lines.append(_h2("Tech Stack", ws.tech_stack))

    if ws.architecture:
        lines.append(_h2_text("Architecture", ws.architecture))

    if ws.conventions:
        lines.append(_h2("Conventions", ws.conventions))

    if ws.structure:
        lines.append("## Project Structure\n")
        for path, description in ws.structure.items():
            lines.append(f"- `{path}` – {description}")
        lines.append("")

    if ws.gotchas:
        lines.append(_h2("Gotchas / Watch-outs", ws.gotchas))

    # Android Agent Stack section (v1.1)
    if ws.android_agent_stack:
        stack = ws.android_agent_stack
        lines.append("## Android Agent Stack\n")
        if stack.get("cli_version"):
            lines.append(f"- **Android CLI version:** {stack['cli_version']}")
        if stack.get("kb_status"):
            lines.append(f"- **Knowledge Base:** {stack['kb_status']}")
        if stack.get("enabled_skills"):
            lines.append("- **Enabled Skills:**")
            for skill in stack["enabled_skills"]:
                lines.append(f"  - {skill}")
        lines.append("")

    return "\n".join(lines)


def workspace_from_project_info(info: ProjectInfo) -> WorkspaceModel:
    """Build a WorkspaceModel from a ProjectInfo (Phase 0 output)."""
    tech_stack: list[str] = info.frameworks.copy()
    if info.languages:
        tech_stack.extend(info.languages)
    if not tech_stack:
        tech_stack = [info.project_type.value]

    architecture = ""
    gotchas: list[str] = []
    structure: dict[str, str] = {}
    conventions: list[str] = []
    android_agent_stack: dict[str, Any] = {}

    pt = info.project_type.value
    if pt == "android":
        architecture = (
            "Android application using Gradle build system. "
            "Standard Android project structure with app module."
        )
        if info.android_package:
            structure["app/src/main/"] = (
                f"Main source code (package: {info.android_package})"
            )
        gotchas.append("Never commit keystore files or google-services.json")
        gotchas.append("local.properties contains machine-specific SDK paths")
        conventions = ["Follow Android Kotlin style guide", "Prefer coroutines for async"]
        if info.android_min_sdk:
            conventions.append(f"Min SDK: {info.android_min_sdk}")

        # Populate Android agent stack
        android_agent_stack = {
            "cli_version": "available" if info.android_cli_available else "not detected",
            "kb_status": info.knowledge_base_status,
            "enabled_skills": info.detected_skills,
        }

        # Add doc summary findings to architecture
        if info.doc_summary:
            arch_findings: list[str] = []
            for _doc, headers in info.doc_summary.items():
                kw_found = [
                    h.replace("[keyword:", "").rstrip("]")
                    for h in headers
                    if h.startswith("[keyword:")
                ]
                if kw_found:
                    arch_findings.extend(kw_found)
            if arch_findings:
                unique_kw = list(dict.fromkeys(arch_findings))
                architecture += f" Detected architecture patterns: {', '.join(unique_kw[:5])}."

    elif pt == "ios":
        architecture = (
            "iOS application. "
            "Standard Xcode project structure."
        )
        if info.ios_bundle_id:
            structure["*.xcodeproj"] = f"Xcode project (bundle: {info.ios_bundle_id})"
        gotchas.append("Never commit .p12 certificates or .mobileprovision files")
        gotchas.append("GoogleService-Info.plist contains sensitive Firebase config")
        conventions = ["Follow Swift API Design Guidelines", "Prefer async/await for concurrency"]

    if info.has_ci:
        conventions.append("CI is configured – ensure tests pass before merging")

    return WorkspaceModel(
        project_name=info.project_name,
        tech_stack=tech_stack,
        architecture=architecture,
        conventions=conventions,
        structure=structure,
        gotchas=gotchas,
        android_agent_stack=android_agent_stack,
    )


# ---------------------------------------------------------------------------
# Copilot instructions generation
# ---------------------------------------------------------------------------


def render_copilot_instructions(
    plan: PlanModel,
    workspace: WorkspaceModel,
    session_id: str,
) -> str:
    """Generate .github/copilot-instructions.md content."""
    tasks_md = "\n".join(f"{i}. {t}" for i, t in enumerate(plan.tasks, 1))
    dod_md = "\n".join(f"- {d}" for d in plan.definition_of_done)

    android_section = ""
    if workspace.android_agent_stack:
        stack = workspace.android_agent_stack
        skills = stack.get("enabled_skills", [])
        android_section = f"""
## Android Agent Stack

- **CLI Available:** {stack.get('cli_version', 'unknown')}
- **Knowledge Base:** {stack.get('kb_status', 'unknown')}

### Best Practices

- Always use `android` CLI commands for emulator and device management within the worktree
- Reference enabled skills when implementing features: {', '.join(skills) if skills else 'none detected'}
- Prefer Jetpack Compose patterns where applicable
- Use Android-specific coroutine dispatchers (Dispatchers.IO for I/O, Dispatchers.Main for UI)
"""

    return f"""\
# Copilot Agent Instructions (KoteGuard Session: {session_id})

> **This is an isolated git worktree. You are NOT in the primary repository.**
> Changes here are safe to experiment with.

## Project: {workspace.project_name}

**Tech Stack:** {', '.join(workspace.tech_stack)}

## Your Mission: {plan.title}

### Tasks

{tasks_md}

### Definition of Done

{dod_md}

## Constraints

- Only modify files relevant to the tasks above.
- Do NOT run `git push` or create pull requests without human review.
- Do NOT access the internet except to install declared dependencies.
- Keep commits small and well-described.

## Token & Context Discipline

- Batch all sub-tasks into a single response where possible
- Use fast/haiku models for drafts, full models for real implementation
- Sessions auto-compact at ~80% context window
{android_section}
## Estimated Time

{plan.estimated_time}
"""


def render_security_instructions(project_type: str = "unknown") -> str:
    """Generate .github/instructions/security.instructions.md content."""
    android_section = ""
    ios_section = ""

    if project_type in ("android", "monorepo", "unknown"):
        android_section = """
### Android

- NEVER read, copy, or output contents of: `*.jks`, `*.keystore`, `google-services.json`
- `local.properties` must never be committed
- Do not add signing config with hardcoded passwords

### Android CLI Commands

**Allowed:** `android list avd`, `android list targets`, `android list sdk`
**Forbidden (outside worktree):** `android run`, `android emulator` – only valid inside a kote worktree
"""

    if project_type in ("ios", "monorepo", "unknown"):
        ios_section = """
### iOS

- NEVER read, copy, or output contents of: `*.p12`, `*.mobileprovision`, `GoogleService-Info.plist`
- Do not hardcode API keys or bundle IDs in source files
"""

    return f"""\
---
applyTo: "**/*"
---

# Security Instructions (KoteGuard)

> These instructions apply to ALL files in this worktree.

## Deny-by-Default Rules

1. **No secrets in source code** – never hardcode API keys, tokens, passwords.
2. **No git push** – humans review all changes before they leave this worktree.
3. **No branch creation outside kote/** – stay on the assigned branch.
4. **No file exfiltration** – do not print or upload file contents to external services.
{android_section}{ios_section}
## Allowed Git Commands

- `git status`, `git diff`, `git log` – read-only inspection
- `git add`, `git commit` – staging and committing changes
- `git stash` – temporary stash

## Forbidden Git Commands

- `git push` – forbidden without human review
- `git remote add` – forbidden
- `git remote set-url` – forbidden
- `git clone` – forbidden inside worktree
"""
